In [1]:
from teehr import Evaluation
from pathlib import Path
import shutil


from bokeh.io import output_notebook
output_notebook()

#### Set-Up from S3 

from the 'clone_from_s3.ipynb' example

set-up: https://rtiinternational.github.io/teehr/getting_started/index.html

In [2]:
# Set a path to the directory where the evaluation will be created
TEST_STUDY_DIR = Path(Path().home(), "temp", "test_study")
shutil.rmtree(TEST_STUDY_DIR, ignore_errors=True)
TEST_STUDY_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
# Create an Evaluation object
ev = Evaluation(dir_path=TEST_STUDY_DIR)

24/12/17 15:33:08 WARN Utils: Your hostname, Dev-VM-Ubuntu-22 resolves to a loopback address: 127.0.1.1; using 10.0.2.15 instead (on interface enp0s3)
24/12/17 15:33:08 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/12/17 15:33:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
ev.list_s3_evaluations()

,name,description,url
0,e0_2_location_example,Example evaluation datsets with 2 USGS gages,s3a://ciroh-rti-public-data/teehr-data-warehou...
1,e1_camels_daily_streamflow,Daily average streamflow at ther Camels basins,s3a://ciroh-rti-public-data/teehr-data-warehou...
2,e2_camels_hourly_streamflow,Hourly instantaneous streamflow at ther Camels...,s3a://ciroh-rti-public-data/teehr-data-warehou...
3,e3_usgs_hourly_streamflow,Hourly instantaneous streamflow at USGS CONUS ...,s3a://ciroh-rti-public-data/teehr-data-warehou...

In [5]:
ev.clone_from_s3("e0_2_location_example")

24/12/17 15:33:13 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
24/12/17 15:33:32 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

#### Working Example

In [6]:
df = ev.primary_timeseries.to_pandas()

In [7]:
df.head(10)

,reference_time,value_time,value,unit_name,location_id,configuration_name,variable_name
0,NaT,2000-10-01 00:00:00,3.341388,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
1,NaT,2000-10-01 01:00:00,3.992675,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
2,NaT,2000-10-01 02:00:00,4.445745,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
3,NaT,2000-10-01 03:00:00,5.408518,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
4,NaT,2000-10-01 04:00:00,5.606736,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
5,NaT,2000-10-01 05:00:00,5.153666,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
6,NaT,2000-10-01 06:00:00,4.559012,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
7,NaT,2000-10-01 07:00:00,5.295250,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
8,NaT,2000-10-01 08:00:00,7.730499,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst
9,NaT,2000-10-01 09:00:00,9.825946,m^3/s,usgs-14138800,usgs_observations,streamflow_hourly_inst

In [8]:
df.teehr.timeseries_plot()

#### Kill spark session

In [9]:
ev.spark.stop()